---
dest_dir: "{{ ansible_env.HOME }}/.local/debinst"
iso_label: "preseed"

preseed_country: DE

preseed_netcfg_interface: enp6s0
preseed_hostname: <insert hostname>
preseed_domain: <insert domain>

preseed_timezone: Europe/Berlin

# These should live in a vault
root_password: root

default_user_fullname: "The Admin"
default_user_name: administrator
default_user_password: administrator
default_user_uid: 1000

# Optional
additional_packages: ""
