---
- name: Play to build preseeded debian image
  hosts: localhost
  gather_facts: true
  become: false

  pre_tasks:
    - name: Load config(s)
      include_vars: "{{ item }}"
      loop:
        - defaults.yml
        - config.yml

    - name: Ensure dest exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: "0744"

  tasks:
    - name: Download ISO
      import_tasks: tasks/download.yml

    - name: Extract ISO
      import_tasks: tasks/extract.yml

    - name: Do the preseed thing
      import_tasks: tasks/preseed.yml

    - name: Repack ISO
      import_tasks: tasks/repack.yml

# vim: ft=yaml.ansible
